name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      

      
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
    - name: Ignore SSH host key checking
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/config
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
      
    - name: Deploy code
      run: |
        ssh root@inovaestudios.com.br "cd /dados/webapps/ecommerce && npm install && git pull"
